# Generated by Django 5.1 on 2025-03-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('frc', models.CharField(blank=True, max_length=10, null=True)),
                ('current_speed', models.FloatField(blank=True, null=True)),
                ('free_flow_speed', models.FloatField(blank=True, null=True)),
                ('current_travel_time', models.IntegerField(blank=True, null=True)),
                ('free_flow_travel_time', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
